kind: "Template"
apiVersion: "v1"
metadata:
  name: ig
  annotations:
objects:
- apiVersion: kops/v1alpha2
  kind: InstanceGroup
  metadata:
    labels:
      kops.k8s.io/cluster: $(CLUSTER_NAME)
    name: master-$(AZ_1)
  spec:
    image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
    machineType: t2.medium
    maxSize: 1
    minSize: 1
    nodeLabels:
      kops.k8s.io/instancegroup: master-$(AZ_1)
    role: Master
    subnets:
    - $(AZ_1)
- apiVersion: kops/v1alpha2
  kind: InstanceGroup
  metadata:
    labels:
      kops.k8s.io/cluster: $(CLUSTER_NAME)
    name: master-$(AZ_2)
  spec:
    image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
    machineType: t2.medium
    maxSize: 1
    minSize: 1
    nodeLabels:
      kops.k8s.io/instancegroup: master-$(AZ_2)
    role: Master
    subnets:
    - $(AZ_2)
- apiVersion: kops/v1alpha2
  kind: InstanceGroup
  metadata:
    labels:
      kops.k8s.io/cluster: $(CLUSTER_NAME)
    name: master-$(AZ_3)
  spec:
    image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
    machineType: t2.medium
    maxSize: 1
    minSize: 1
    nodeLabels:
      kops.k8s.io/instancegroup: master-$(AZ_3)
    role: Master
    subnets:
    - $(AZ_3)
- apiVersion: kops/v1alpha2
  kind: InstanceGroup
  metadata:
    labels:
      kops.k8s.io/cluster: $(CLUSTER_NAME)
    name: nodes
  spec:
    image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
    machineType: t2.medium
    maxSize: 2
    minSize: 2
    nodeLabels:
      kops.k8s.io/instancegroup: nodes
      instance_group: nodes
    role: Node
    subnets:
    - $(AZ_1)
parameters:
  - name: "CLUSTER_NAME"
    required: true
    parameterType: "string"
  - name: "AZ_1"
    required: true
    parameterType: "string"
  - name: "AZ_2"
    required: true
    parameterType: "string"
  - name: "AZ_3"
    required: true
    parameterType: "string"
